### ISSUE TITLE
Travis CI should produce our builds for us

### ISSUE THREAD

**Issue by Artheau** [Artheau/SpriteSomething#36] opened 2019-07-28 22:03 UTC
That way we can quickly release executables on many platforms.

**Comment by miketrethewey** [comment] 2019-07-31 01:26
#39 handled most of this.
Last sticking point is grokking the credentials handshake between Travis & GitHub.

Design that we've adopted is as follows:
- Travis
	- Test Phase
		- Spin up VM
		- Check out repo at commit/merge
		- Install dependencies
		- Run `tests.py`
		- Destroy VM
	- Build Phase (if Test Phase passes)
		- Spin up VM
		- Check out repo at commit/merge
		- Install dependencies
		- Run `build.py`
		- Deploy Phase (if Build Phase passes; technically still part of Build Phase; only from `branch: master`)
			- Deploy only if 3.7 on Bionic, 3.7 on MacOSX, 3.7 on Windows (Don't care about Xenial since we're superceding it by 3.7 & Bionic, but still testing for good measure)
			- Build filename is `SpriteSomething-<travis_build_number>-<platform>` (`*.exe` if Windows)
			- Deploy to same Git tag eventually in form of `<major>.<minor>.<travis_build_number>`
			(Presently just as `<travis_build_number>` until I finalize the solution for the first one)
		- Destroy VM
		- (Builds are lost if not deployed; can definitely still build from source on local machine)

Prior to getting credentials handshake grokked, Deploy Phase is broken, but Art & Mike can build locally on Windows (natively); Mike can build locally on Lubuntu (local VM), and a release with binaries can be uploaded manually.

**Comment by miketrethewey** [comment] 2019-08-01 12:09
Use package `zip` to archive binary into a nice package with the source code and inject the compiled version number that's exported to `/app_resources/meta/manifests/app_version.txt` and thusly read into `APP_VERSION` via `constants.py`.

**Comment by miketrethewey** [comment] 2019-08-06 03:00
Consider using [GitHub Releaser CLI for Travis-CI](https://github.com/lindell/github-release-cli) if we want custom body text on the release at posting that can be pulled from an included markdown file.

**Comment by miketrethewey** [comment] 2019-08-09 10:41
lindell/github-release-cli#3

**Comment by miketrethewey** [comment] 2019-08-30 09:17
Bionic build works on Disco.

**Comment by miketrethewey** [comment] 2020-03-03 11:47
Artheau/SpriteSomething@712df88 is proving to be close to working as intended with GitHub Actions instead.

**Comment by miketrethewey** [comment] 2020-03-15 21:51
Merged as of d012405 using GitHub Actions. GHPages publishing still pending testing.

**Closed by miketrethewey** 2020-03-15 21:51 UTC
Labels: feature request, pending review
